name: CI/CD Pipeline

on:
  push:
    branches:
      - wftest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            ls
            cd RPS-backend
            git pull
            git status
            cd ..
            docker-compose build backend
            docker-compose up -d backend